# Generated by Django 2.0.2 on 2018-09-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_codeblog_readcodeblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readcodeblog',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_codeblogtitle', to='blog.Codeblog'),
        ),
    ]
